name: Editor publication

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release (yes/no)'
        required: false
        default: 'no'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Set publication type
        if: ${{ github.event.inputs.release == 'yes' }}
        run: |
          echo "release_parameter=-Prelease" >> $GITHUB_ENV
      - name: Publish Editor with Gradle
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEYID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          cd component/editor
          chmod +x ../gradlew
          ../gradlew publish ${{ env.release_parameter }}
      - name: Release
        if: ${{ github.event.inputs.release == 'yes' }}
        run: |
          cd component
          ./gradlew closeAndReleaseRepository
        env:
          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.NEXUS_PASSWORD }}
